config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :reservations

  root 'home#index'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:location, :destination, :pickup_time, :auto_type, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/home/index.html.erb
<div class="background-orbit">
			
			<ul class="example-orbit" data-orbit data-options="animation:slide; pause_on_hover:true; animation_speed:500; navigation_arrows:true; bullets:false;">
				<li> 
					<img src="/assets/escalade_lg.jpg" alt="slide 1" /> 
					<div class="orbit-caption"> Escalade</div> 
				</li> 
				<li class="active"> 
					<img src="/assets/escalade_lg.jpg" alt="slide 2" /> 
					<div class="orbit-caption"> Town Car</div>
				 </li>
				<li> 
					<img src="/assets/escalade_lg.jpg" alt="slide 3" />
					<div class="orbit-caption" >Sprinter </div> 
				</li>
			</ul>		
	<!-- </div> -->
</div>	

<div class="background-mid">
<div class="row"> 
	<div class="row">
		<div class="small-6 large-4 columns"><h4></h4></div>
		<div class="small-6 large-4 columns" align="center"><h4>Reservation</h4></div>
		<div class="small-6 large-4 columns"><h4></h4></div>
	</div>
	 <div class="row">
	<div class="small-6 columns">	
	<%= form_tag("/reservation", method: "post") do %>
		<%= datetime_local_field(:reservation, :pickup_time) %>
		<%= datetime_local_field(:reservation, :pickup_time) %>
		<%= datetime_local_field(:reservation, :pickup_time) %>	
	</div>	

	<div class="small-6 columns">
		<%= datetime_local_field(:reservation, :pickup_time) %>
		<%= datetime_local_field(:reservation, :pickup_time) %>
		<%= datetime_local_field(:reservation, :pickup_time) %>
		<% end %>
    </div>
	</div>
	    <div class="row">
			<div class="small-6 large-4 columns"><h4></h4></div>
			<div class="small-6 large-4 columns" align="center"> <a href="#" class="button radius">Reserve</a></div>
			<div class="small-6 large-4 columns"><h4></h4></div>
		</div>	
  </div>
</div>


<div class="row"> 
	</hr>
	<ul class="small-block-grid-2 large-block-grid-4">
	    <li><img src="/assets/photo.jpg"></li>
	    <li><img src="/assets/photo.jpg"></li>  
	    <li><img src="/assets/photo.jpg"></li>
	    <li><img src="/assets/photo.jpg"></li>   
	</ul>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  
  <div class="background-top"> 
 
    <div class="row"> 
     

        <nav class="top-bar" data-topbar role="navigation"> 
          <ul class="title-area"> 
            <li class="name"> <h1><a href="#">Company Name</a></h1> </li>
             <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
              <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
          </ul> <section class="top-bar-section">
           <!-- Right Nav Section -->
          <ul class="right"> 
            <li class="active"><a href="#">Right Button Active</a></li>
            <li class="has-dropdown"> <a href="#">Right Button Dropdown</a> 
            <ul class="dropdown"> <li><a href="#">First link in dropdown</a></li>
              <li class="active"><a href="#">Active link in dropdown</a></li>
            </ul> 
            </li> 
          </ul> 
            <!-- Left Nav Section --> <ul class="left"> <li><a href="#">Left Nav Button</a></li> </ul> </section>
         </nav> 
    </div>
</div>
        <%= yield %>
 
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :pickup_time %><br>
    <%= f.datetime_select :pickup_time %>
  </div>
  <div class="field">
    <%= f.label :auto_type %><br>
    <%= f.text_field :auto_type %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Destination</th>
      <th>Pickup time</th>
      <th>Auto type</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.location %></td>
        <td><%= reservation.destination %></td>
        <td><%= reservation.pickup_time %></td>
        <td><%= reservation.auto_type %></td>
        <td><%= reservation.email %></td>
        <td><%= reservation.phone %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @reservation.location %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @reservation.destination %>
</p>

<p>
  <strong>Pickup time:</strong>
  <%= @reservation.pickup_time %>
</p>

<p>
  <strong>Auto type:</strong>
  <%= @reservation.auto_type %>
</p>

<p>
  <strong>Email:</strong>
  <%= @reservation.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @reservation.phone %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>